### PR TITLE
Add way to trigger render from page that is being rendered

### PR DESCRIPTION
**Pull request by marcbachmann**
The delay in here doesn't respect the `onLoadFinished` event.
Maybe we have to set up the delay after that got triggered.
@chriskinsman what do you think. That's what you did in your pr.

### CODE REVIEW

**Comment by chriskinsman** [comment]
Yep.  It should be post onLoadFinished.

**Comment by marcbachmann** [comment]
👍 

I'll cherry-pick those tests after you've commited.
https://github.com/marcbachmann/node-html-pdf/pull/173/files

**Comment by chriskinsman** [comment]
Thinking it might make sense to just close this pull request and I will submit a new one with this functionality since it conflates the delay and the page triggered render...

**Comment by marcbachmann** [comment]
Yep, you can work on the other branch (also a pr) if you like.
https://github.com/marcbachmann/node-html-pdf/tree/render-delay

**Comment by marcbachmann** [comment]
Ah, I didn't get that you renamed that issue title. Was confused a bit.
Feel free to open a new pr.

**Comment by chriskinsman** [comment]
I think my new PR #263 solves this

**Pull request closed without merging**
